# Generated by Django 2.2.10 on 2020-10-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permission',
        ),
        migrations.AddField(
            model_name='role',
            name='create_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='delete_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='read_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='update_access',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
