# Generated by Django 2.2.10 on 2020-10-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201002_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geotag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('pending', 'Pending'), ('solved', 'Solved')], max_length=100, null=True)),
                ('description', models.CharField(blank=True, choices=[('pending', 'Pending'), ('solved', 'Solved')], max_length=200, null=True)),
                ('type', models.CharField(blank=True, choices=[('pending', 'Pending'), ('solved', 'Solved')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('solved', 'Solved')], max_length=20, null=True)),
                ('location', models.CharField(blank=True, choices=[('pending', 'Pending'), ('solved', 'Solved')], max_length=500, null=True)),
                ('file', models.CharField(blank=True, choices=[('pending', 'Pending'), ('solved', 'Solved')], max_length=100, null=True)),
            ],
        ),
    ]
