# Generated by Django 2.2.10 on 2020-10-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201005_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotag',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
