# Generated by Django 2.2.10 on 2020-10-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201005_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotag',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='location',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
