# Generated by Django 2.2.10 on 2020-10-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201005_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='geotag',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='geotag',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
