# Generated by Django 2.2.10 on 2020-10-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201006_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotag',
            name='type',
            field=models.CharField(blank=True, choices=[('point', 'Point'), ('linestring', 'Line'), ('polygon', 'Polygon')], max_length=20, null=True),
        ),
    ]
