# Generated by Django 2.2.10 on 2020-10-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201007_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotag',
            name='location',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
