# Generated by Django 2.2.10 on 2020-10-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201008_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotag',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('investigate', 'Under Investigation'), ('action', 'In Action'), ('solved', 'Solved')], default='pending', max_length=20, null=True),
        ),
    ]
